### ISSUE TITLE
LENGTH cutoff for the minimum length of a deletion is giving error

### ISSUE THREAD

**Issue by Him22** [Runsheng/primervcf#4]
Hi Runsheng,

Using the LENGTH (-l) cutoff option for the minimum length of a deletion to be selected for primer design is giving following error,
without giving --length (-l) option it is working fine
I want to design the primers for regions having deletion of >= 20 nt.

vcf2del.py -f QR25.vcf -o QR25_del.bed -l 20
Traceback (most recent call last):
  File "mambaforge/envs/py39/bin/vcf2del.py", line 29, in <module>
    bed_l=get_deletion_region(args.file, key="del", len_cutoff=args.length)
  File "mambaforge/envs/py39/lib/python3.9/site-packages/primervcf/vcfparser.py", line 92, in get_deletion_region
    if del_len>=len_cutoff and "n" not in record.REF: # no gap in the reference
TypeError: '>=' not supported between instances of 'int' and 'str'

please help to resolve this issue.
Best regards
Himanshu

**Comment by Runsheng** [comment]
Sorry for the old bug. Should have been fixed in the github repo. 

Would you please help to test the new fix with github install using the following code?
```
git clone https://github.com/Runsheng/primervcf.git
cd primervcf
pip install .
```

Best regards,
Runsheng

**Comment by Runsheng** [comment]
close with 0.1.5 in pip
