### ISSUE TITLE
The first filtered sites isn't all INDEL.

### ISSUE THREAD

**Issue by 5katerina** [Runsheng/primervcf#5]
Hi Runsheng, I had an error when using this code. 
As the first screenshot below, the detail of the second step is on the left, while the corresponding result after the first step is on the right. When I get the result after using the whole code, I check my original document to find out how many samples the result can separate. However, the site where second & third successful design primer doesn't appear INDEl in fact as the next two screenshot.
Please help to resolve this issue.
Best regards.
Huangyan
<img width="584" alt="截屏2023-08-08 09 51 47" src="https://github.com/Runsheng/primervcf/assets/141696672/31c3c7c6-6796-4e0f-bfd7-45854fc98945">
![截屏2023-08-08 10 05 01](https://github.com/Runsheng/primervcf/assets/141696672/4a32d950-efbf-4a9e-8cdf-61f5dde7df07)
![截屏2023-08-08 10 02 41](https://github.com/Runsheng/primervcf/assets/141696672/f515e365-5231-48b9-942b-1f9452722d14)

**Comment by Runsheng** [comment]
Hi Huangyan,

Sorry the VCF filter used in primervcf is a very simple one. It can not handle low-quality variations like the ones shown in your later screenshots (DP=0). You can first filter your VCF to retain only the reliable variations, like using DP>10 and mapq>30.

Best regards,
Runsheng

**Comment by 5katerina** [comment]
No wonder, I got it.
Thank you for your reply.

With kind regards.
Huangyan
